config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :posters do
    resources :transactions, only: %i[show new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poster.rb
class Poster < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader
  validates :venue_name, :artist_name, :description, :price, :photo, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :poster
  belongs_to :user

  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posters
  has_many :transactions
  validates :username, :bio, :avatar, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:home, :show]
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posters = Poster.all
  end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  before_action :find_poster, only: [:show, :edit, :update, :destory]

  def index
    if params[:query].present?
      sql_query = "posters.description ILIKE :query OR posters.venue_name ILIKE :query"
      @posters = Poster.where(sql_query, query: "%#{params[:query]}%")
    else
      @posters = Poster.all
    end
  end


  def show
  end

  def new
    @poster = Poster.new
  end

  def create
    @poster = Poster.new(poster_params)
    @poster.user = current_user
    if @poster.save
        redirect_to poster_path(@poster)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @poster.update(poster_params)
    redirect_to poster_path(params[:id])
  end

  def destroy
  end

  private

  def find_poster
    @poster = Poster.find(params[:id])
  end

  def poster_params
    params.require(:poster).permit(:artist_name, :venue_name, :description,
      :date, :price, :photo)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @poster = Poster.find(params[:poster_id])
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(date: Date.today)
    @transaction.user = current_user
    @transaction.poster = Poster.find(params[:poster_id])
    @poster = @transaction.poster
    if @transaction.save
      @poster.sold = true
      @poster.save
      redirect_to poster_path(@transaction.poster)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'noun_movie_1585351_E1O_icon.ico' %>
    <title>Movie compare</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image:  url('https://res.cloudinary.com/cocktailsdelivereddotcom/image/upload/v1537191430/georgia-vagim-381292-unsplash.jpg');">

  <div class="banner-content">
    <h1>Movie Exchange </h1>
    <p>An Online source for all types of Movies </p>
  </div>

    <div class="scroll-indicator fa fa-chevron-down"></div>

  </div>
</div>


<div class="container">
  <div class="row">
    <%= render 'shared/card' %>
  </div>
</div>

<div class="footer">
  <div class="footer-links">

  </div>
  <div class="footer-copyright">
    <p>.................This is a concept site, and does not sell or endorse any of the listed vendors</p>

  </div>
</div>

app/views/posters/edit.html.erb
<%= render 'shared/poster_details' %>

app/views/posters/index.html.erb
<!-- <div class="banner" style="background-image: url('https://res.cloudinary.com/duspt82gb/image/upload/v1534947776/view_in_room.jpg');">
  <div class="banner-content">
    <h1>Find Gig Posters</h1>
    <p>from the best night of your life</p>
    <p><i class="fas fa-chevron-down"></i></p>
    <p><i class="fas fa-chevron-down"></i></p>
  </div>
</div>
 -->

<div class="container">
  <div class="row">
    <%= render 'shared/card' %>
  </div>
</div>

app/views/posters/new.html.erb
<div class="wrapper">
  <div class="container sell-page">
  <div>
    <h1>List a new poster for sale</h1>
  </div>
    <%= render 'shared/poster_details' %>
  </div>
</div>

app/views/posters/show.html.erb
<div class="container show-details">
  <div class="row">
    <div class="col-sm-5 image-display-sell">
      <%# image_tag url('@poster.photo'), width: '400', height: '600', align: 'left'%>
      <% if @poster.sold %>
        <div class="stick-together">
          <%= cl_image_tag @poster.photo, width: 405, crop: :fill %>
          <%= image_tag "sold.png", alt: "alttext", class: "sold", style: "height: 120px;" %>
        </div>
      <% else %>
       <%= cl_image_tag @poster.photo, width: 405, crop: :fill %>
      <% end %>
    </div>
    <div class="col-sm-7 poster-desciption-show">
      <h2><%= @poster.artist_name%></h2>
      <h1><i class="fas fa-angle-double-left"></i> <%= @poster.description %> <i class="fas fa-angle-double-right"></i></h1>
      <h3>type: <%= @poster.venue_name %></h3>
      <!-- <h3></%> purchased On: <%= @poster.date.strftime("#{@poster.date.day.ordinalize} %B %Y") %></h3> -->
      <% if @poster.sold %>
        <h1><strike>£<%= @poster.price %></strike></h1>

        <h3>Alternatively find an online version</h3>

      <img class="provider-filter__icon" ng-src="https://images.justwatch.com/icon/4610466/s100/sky-store" alt="Sky Store" title="Sky Store" ng-if="::(!isCloaked(provider.id) || inBigBrotherMode === false)" fader-on-load="" src="https://images.justwatch.com/icon/4610466/s100/sky-store" style="opacity: 1;">

      <img class="provider-filter__icon" ng-src="https://images.justwatch.com/icon/52449539/s100/amazon-prime-video" alt="Amazon Prime Video" title="Amazon Prime Video" ng-if="::(!isCloaked(provider.id) || inBigBrotherMode === false)" fader-on-load="" src="https://images.justwatch.com/icon/52449539/s100/amazon-prime-video" style="opacity: 1;">


      <% else %>
        <h1>£<%= @poster.price %> </h1>



      <% end %>
      <% if @poster.sold %>
        <p></p>
      <% else %>



     <button type="button" class="btn btn-lg btn-info" data-toggle="tooltip" data-placement="right" title="Please note this is a concept site and you will not be buying this item">
      <%= link_to "Buy Now", new_poster_transaction_path(@poster.id) %>
     </button>




      <% end %>
      <div class="seller">
        <div style="width:100%; height:1px; border: 1px solid #F23A3A"></div>
        <div>
          <%= image_tag @poster.user.avatar, alt: "alttext", style: "margin-top:-30px;", class: "avatar" %>
        </div>
        <div class="seller-contact">
          <%= @poster.user.username %>
        </div>
        <div class="btn btn-sml btn-primary seller-btn">  <p>Contact Seller</p>
        </div>
        <div class="seller-bio">
          <i class="fas fa-quote-left"></i>
          <%= @poster.user.bio %>
          <i class="fas fa-quote-right"></i>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<% @posters.each do |poster| %>
  <div class="col-xs-12 col-sm-3">
    <div class="card" >
      <div class="card-container" style="background-image: url(<%= poster.photo %>);">
        <% if poster.sold %>
          <%= image_tag "sold.png", alt: "alttext", class: "sold", style: "height: 120px;" %>
        <% end %>
      </div>
      <div class="info-holder">
        <div class="card-description">
          <h4><%= poster.description %></h4>
          <% if poster.sold %>
            <h4><strike>£<%= poster.price %></strike></h4>
          <% else %>
            <h4>£<%= poster.price %> </h4>
          <% end %>
        </div>
        <div class="date-place">
          <p> <%= poster.venue_name %>
          </p>
        </div>
      </div>
    </div>
    <%= link_to "", poster_path(poster.id), class: "card-link" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <div class="nav-search">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag 'https://res.cloudinary.com/cocktailsdelivereddotcom/image/upload/v1537211894/noun_Movie_1585351.png', height: 50 %>
    <% end %>
    <div class="search-bar">
      <%= form_tag posters_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          id: "roundedsearch",
          class: "form-control",
          placeholder: "Find a movie..." %>
      <span id="magnify" class="icon"><i id="mag" class="fa fa-search"></i></span>
    </div>
  </div>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "Home",  root_path,  class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sell", new_poster_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle"=>"dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <li><a href="#">Profile</a></li>
              <li><a href="#">Dashboard</a></li>
              <li>              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %></li>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_poster_details.html.erb
<div class="container">
  <div class="sell-div">
    <div class="image">
      <%#= image_tag , alt: "alttext", size: "550x700" %>
    </div>
    <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
        <%= simple_form_for @poster do |f| %>
          <%= f.input :artist_name, label: "Which actor was staring?" %>
          <%= f.input :venue_name, label: "Which format is your film" %>
          <%= f.input :description, label: "Film's Title" %>
          <%= f.input :date, as: :string, input_html: { class: "datepicker" }, label: "What date was the film purchased?", required: false %>
          <%= f.input :price, label: "Price in GBP" %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit "List Movie for sale!", class: "sell-btn btn-lg btn btn-danger" %>
        <% end %>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="container show-details">
  <div class="row">
    <div class="col-sm-5 image-display-sell">
      <img src=" <%= @poster.photo %> "
      style="width: 405px;">
    </div>
    <div class="col-sm-7 title-red">
      <h2>You pay £<%= @poster.price %> to:</h2>
      <div class="seller">
        <div style="width:100%; height:1px; border: 1px solid #F23A3A"></div>
        <div>
          <%= image_tag @poster.user.avatar, alt: "alttext", style: "margin-top:-30px;", class: "avatar" %>
        </div>
        <div class="seller-contact">
          <%= @poster.user.username %>
        </div>

        <div class="payment form">

         </div>


        <div class="confirm-button">



          <%= simple_form_for([@poster, @transaction]) do |f| %>
            <%= f.submit "Confirm Purchase", class: "btn btn-lg btn-warning" %>
          <% end %>
          </div>
      </div>
        <div>


<!--       <h2 style="text-align: right;">£<%= @poster.price %></h2> -->
    </div>
  </div>
</div>